# Generated by Django 4.1.1 on 2022-09-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_music_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="path",
            field=models.FileField(upload_to=""),
        ),
    ]
