# Generated by Django 4.1.1 on 2022-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_music_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="name",
            field=models.FileField(max_length=50, upload_to=""),
        ),
        migrations.AlterField(
            model_name="music",
            name="path",
            field=models.FilePathField(),
        ),
    ]
