# Generated by Django 4.1.1 on 2022-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_music_name_alter_music_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="file",
            field=models.FileField(default=1, upload_to="musics/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="music",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="music",
            name="path",
            field=models.CharField(max_length=200),
        ),
    ]
